# Generated by Django 3.1.1 on 2021-03-07 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=200)),
                ('wesite_logo1', models.ImageField(upload_to='')),
                ('wesite_logo2', models.ImageField(upload_to='')),
                ('wesite_favicon', models.ImageField(upload_to='')),
                ('website_url', models.URLField()),
                ('website_is_rtl', models.BooleanField(default=0)),
                ('website_language', models.IntegerField(default=0)),
                ('website_is_search', models.BooleanField(default=0)),
                ('website_is_active', models.BooleanField(default=1)),
                ('website_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('website_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('website_homepage_id', models.IntegerField(default=0)),
                ('website_template_id', models.IntegerField(default=0)),
                ('website_visitor_count', models.IntegerField(default=0)),
                ('website_primary_font_id', models.IntegerField(default=0)),
                ('website_secondary_font_id', models.IntegerField(default=0)),
                ('website_primary_font_style_id', models.IntegerField(default=0)),
                ('website_secondary_font_style_id', models.IntegerField(default=0)),
                ('website_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
