# Generated by Django 3.1.1 on 2021-03-08 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.TextField(default=None)),
                ('page_title', models.CharField(max_length=200)),
                ('page_desc', models.TextField()),
                ('page_author', models.CharField(max_length=200)),
                ('page_is_active', models.BooleanField(default=1)),
                ('page_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_style_id', models.IntegerField(default=0)),
                ('page_name', models.CharField(max_length=200)),
                ('page_is_container', models.BooleanField(default=1)),
                ('page_website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
