# Generated by Django 3.1.1 on 2021-03-08 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_text1', models.CharField(max_length=200)),
                ('counter_count1', models.IntegerField()),
                ('counter_text2', models.CharField(max_length=200)),
                ('counter_count2', models.IntegerField()),
                ('counter_text3', models.CharField(max_length=200)),
                ('counter_count3', models.IntegerField()),
                ('counter_text4', models.CharField(max_length=200)),
                ('counter_count4', models.IntegerField()),
                ('counter_text5', models.CharField(max_length=200)),
                ('counter_count5', models.IntegerField()),
                ('counter_text6', models.CharField(max_length=200)),
                ('counter_count6', models.IntegerField()),
                ('counter_title', models.CharField(max_length=200)),
                ('counter_desc', models.TextField()),
                ('counter_is_active', models.BooleanField(default=1)),
                ('counter_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter_subtitle', models.CharField(max_length=200)),
                ('counter_bg_image', models.ImageField(upload_to='')),
                ('counter_bg_color', models.CharField(max_length=200)),
                ('counter_color', models.CharField(max_length=200)),
                ('counter_button_text', models.CharField(max_length=200)),
                ('counter_button_link', models.TextField()),
                ('counter_is_link_external', models.BooleanField(default=0)),
                ('counter_top_margin', models.IntegerField(default=0)),
                ('counter_top_padding', models.IntegerField(default=0)),
                ('counter_bottom_margin', models.IntegerField(default=0)),
                ('counter_bottom_padding', models.IntegerField(default=0)),
                ('counter_primary_font_id', models.IntegerField(default=0)),
                ('counter_secondary_font_id', models.IntegerField(default=0)),
                ('counter_primary_font_style_id', models.IntegerField(default=0)),
                ('counter_secondary_font_style_id', models.IntegerField(default=0)),
                ('counter_icon1', models.CharField(max_length=200)),
                ('counter_icon2', models.CharField(max_length=200)),
                ('counter_icon3', models.CharField(max_length=200)),
                ('counter_icon4', models.CharField(max_length=200)),
                ('counter_icon5', models.CharField(max_length=200)),
                ('counter_icon6', models.CharField(max_length=200)),
            ],
        ),
    ]
