# Generated by Django 3.1.1 on 2021-03-19 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_pageelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='wesite_favicon',
            new_name='website_favicon',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='wesite_logo1',
            new_name='website_logo1',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='wesite_logo2',
            new_name='website_logo2',
        ),
    ]
