# Generated by Django 3.1.1 on 2021-03-20 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210318_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_user_uname', models.CharField(max_length=200)),
                ('sub_user_pass', models.CharField(max_length=200)),
                ('sub_user_last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_user_is_active', models.BooleanField(default=1)),
                ('sub_user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_user_owner_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_access_is_active', models.BooleanField(default=1)),
                ('sub_access_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_access_owner_id', models.IntegerField(default=0)),
                ('sub_access_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subuser')),
                ('sub_access_website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_in_head_content', models.TextField()),
                ('meta_begin_body_content', models.TextField()),
                ('meta_end_body_content', models.TextField()),
                ('meta_is_active', models.BooleanField(default=1)),
                ('meta_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
