# Generated by Django 3.1.1 on 2021-03-21 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_meta_subuser_subuseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_contact', models.CharField(max_length=200)),
                ('header_email', models.CharField(max_length=200)),
                ('header_facebook', models.CharField(max_length=200)),
                ('header_twitter', models.CharField(max_length=200)),
                ('header_instagram', models.CharField(max_length=200)),
                ('header_is_active', models.BooleanField(default=1)),
                ('header_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('header_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('header_website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
        migrations.CreateModel(
            name='Menu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu1_title', models.CharField(max_length=200)),
                ('menu1_order', models.CharField(max_length=200)),
                ('menu1_link_type', models.CharField(max_length=200)),
                ('menu1_link_url', models.TextField()),
                ('menu1_is_active', models.BooleanField(default=1)),
                ('menu1_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu1_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu1_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.header')),
            ],
        ),
        migrations.CreateModel(
            name='Menu2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu2_title', models.CharField(max_length=200)),
                ('menu2_order', models.CharField(max_length=200)),
                ('menu2_link_type', models.CharField(max_length=200)),
                ('menu2_link_url', models.TextField()),
                ('menu2_is_active', models.BooleanField(default=1)),
                ('menu2_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu2_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu2_menu1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.menu1')),
            ],
        ),
        migrations.CreateModel(
            name='Menu3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu3_title', models.CharField(max_length=200)),
                ('menu3_order', models.CharField(max_length=200)),
                ('menu3_link_type', models.CharField(max_length=200)),
                ('menu3_link_url', models.TextField()),
                ('menu3_is_active', models.BooleanField(default=1)),
                ('menu3_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu3_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu3_menu2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.menu2')),
            ],
        ),
    ]
