# Generated by Django 3.1.1 on 2021-03-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_header_menu1_menu2_menu3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu3',
        ),
    ]
