# Generated by Django 3.1.1 on 2021-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_menu3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu1',
            name='menu1_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu2',
            name='menu2_order',
            field=models.IntegerField(),
        ),
    ]
