# Generated by Django 3.1.1 on 2021-03-25 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210323_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='header_tagline',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
