# Generated by Django 3.1.1 on 2021-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_header_header_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='counter_button_text',
            new_name='counter_icon_color',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_color',
            new_name='counter_number',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_icon5',
            new_name='counter_status',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_icon6',
            new_name='counter_text_color',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_subtitle',
            new_name='counter_title_color',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_bottom_margin',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_bottom_padding',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_button_link',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_count5',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_count6',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_is_link_external',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_primary_font_id',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_primary_font_style_id',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_secondary_font_id',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_secondary_font_style_id',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_text5',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_text6',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_top_margin',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='counter_top_padding',
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_animation_delay',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_animation_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count1_append',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count1_prepend',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count2_append',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count2_prepend',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count3_append',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count3_prepend',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count4_append',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_count4_prepend',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_count1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_count2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_count3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_count4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_icon1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_icon2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_icon3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_icon4',
            field=models.TextField(),
        ),
    ]
