# Generated by Django 3.1.1 on 2021-03-26 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_title', models.CharField(max_length=200)),
                ('counter_desc', models.TextField()),
                ('counter_number', models.CharField(max_length=200)),
                ('counter_icon1', models.TextField()),
                ('counter_text1', models.CharField(max_length=200)),
                ('counter_count1_prepend', models.CharField(default=None, max_length=200)),
                ('counter_count1', models.CharField(max_length=200)),
                ('counter_count1_append', models.CharField(default=None, max_length=200)),
                ('counter_icon2', models.TextField()),
                ('counter_text2', models.CharField(max_length=200)),
                ('counter_count2_prepend', models.CharField(default=None, max_length=200)),
                ('counter_count2', models.CharField(max_length=200)),
                ('counter_count2_append', models.CharField(default=None, max_length=200)),
                ('counter_icon3', models.TextField()),
                ('counter_text3', models.CharField(max_length=200)),
                ('counter_count3_prepend', models.CharField(default=None, max_length=200)),
                ('counter_count3', models.CharField(max_length=200)),
                ('counter_count3_append', models.CharField(default=None, max_length=200)),
                ('counter_icon4', models.TextField()),
                ('counter_text4', models.CharField(max_length=200)),
                ('counter_count4_prepend', models.CharField(default=None, max_length=200)),
                ('counter_count4', models.CharField(max_length=200)),
                ('counter_count4_append', models.CharField(default=None, max_length=200)),
                ('counter_is_active', models.BooleanField(default=1)),
                ('counter_bg_image', models.ImageField(upload_to='')),
                ('counter_bg_color', models.CharField(max_length=200)),
                ('counter_icon_color', models.CharField(max_length=200)),
                ('counter_title_color', models.CharField(max_length=200)),
                ('counter_text_color', models.CharField(max_length=200)),
                ('counter_animation_type', models.CharField(default=None, max_length=200)),
                ('counter_animation_delay', models.CharField(default=None, max_length=200)),
                ('counter_status', models.CharField(max_length=200)),
                ('counter_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
